image: "rust:latest"

tests:
  script:
    - rustc --version && cargo --version
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo test --workspace --verbose --all --locked
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D clippy::all -D unused_must_use -D warnings
