repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ['--all-targets', '--all-features', '--', '-D', 'clippy::all', '-D', 'unused_must_use']
