repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
        args: ['--all-targets']
      - id: clippy
        args: ['--all-targets', '--all-features', '--', '-D', 'clippy::all', '-D', 'unused_must_use', '-D', 'warnings']
