client_id: "id"
client_secret: "secret"
user_agent:
  # empty fields are computed ar runtime
  platform:
  app_id:
  version:
  reddit_username: artslob-api-user
access_token_url: "https://www.reddit.com/api/v1/access_token"
api_base_url: "https://oauth.reddit.com/"
